# local
spring:
  config:
    activate:
      on-profile: local

# local-kakao
kakao:
  auth:
    token-uri: "https://kauth.kakao.com/oauth/token"
    client-id: "c085be75e3063d0cd6c5bfbac24038f4"
    redirect-uri: "http://localhost:8080/auth/kakao/callback"
  user:
    profile-uri: "https://kapi.kakao.com/v2/user/me?secure_resource=false&property_keys=%5B%22kakao_account.profile.profile_image%22%2C%22kakao_account.profile.nickname%22%5D"
# local-naver
naver:
  auth:
    token-uri: "https://nid.naver.com/oauth2.0/token"
    client-id: "xEGDynHBKujCMrZ5M1g1"
    client-secret: "wPumA7iScR"
    redirect-uri: "http://localhost:8080/auth/naver/callback"
  user:
    profile-uri: "https://openapi.naver.com/v1/nid/me"

# local-google
google:
  auth:
    token-uri: "https://oauth2.googleapis.com/token"
    client-id: "195720517800-s52u80t1mhlirk583ec34s4siisldm8d.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:8080/auth/google/callback"
  user:
    profile-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
---
# prod -
spring:
  config:
    activate:
      on-profile: prod
kakao:
  auth:
    token-uri: "https://kauth.kakao.com/oauth/token"
    client-id: "c085be75e3063d0cd6c5bfbac24038f4"
    redirect-uri: "https://국민사형투표.com/auth/kakao/callback"

  user:
    profile-uri: "https://kapi.kakao.com/v2/user/me"

naver:
  auth:
    token-uri: "https://nid.naver.com/oauth2.0/authorize"
    client-id: "xEGDynHBKujCMrZ5M1g1"
    client-secret: "wPumA7iScR"
    redirect-uri: "https://국민사형투표.com/auth/naver/callback"
  user:
    profile-uri: "https://openapi.naver.com/v1/nid/me"

google:
  auth:
    token-uri: "https://oauth2.googleapis.com/token"
    client-id: "195720517800-s52u80t1mhlirk583ec34s4siisldm8d.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://xn--3e0b39y4pd92v9pct9c.com/auth/google/callback"
  user:
    profile-uri: "https://www.googleapis.com/oauth2/v3/userinfo"