version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: "1234"

    command:
      - --character-set-server=UTF8MB4
      - --collation-server=UTF8MB4_UNICODE_CI
      - --lower_case_table_names=1

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes