spring:
  application:
    name: persona-wiki-web

  config:
    import:
      - "jpa.yml"
      - "actuator.yml"
      - "authentication.yml"

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


--- # prod
spring:
  config:
    activate:
      on-profile: prod

logging:
  config: classpath:logback-prod.xml
