global:
  resolve_timeout: 5m
  # 이메일 알림을 보내려면 아래 주석을 해제하고 설정하세요
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_from: 'alertmanager@example.com'
  # smtp_auth_username: 'gmail-account@gmail.com'
  # smtp_auth_password: 'password'

route:
  group_by: [ 'alertname', 'job', 'severity' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'web-hook'
  routes:
    - match:
        severity: critical
      receiver: 'web-hook'
      repeat_interval: 1h

receivers:
  - name: 'web-hook'
    webhook_configs:
      - url: 'http://host.docker.internal:8080/api/alerts'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'admin'
            password: 'ing9990'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: [ 'alertname', 'instance' ]