spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 100

---
# local
storage:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/persona_wiki
    username: root
    password: 1234
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always

---
# prod
storage:
  datasource:
    jdbc-url: jdbc:mysql://persona-wiki.c7emcmko0vuq.ap-northeast-2.rds.amazonaws.com:3306/persona_wiki
    username: admin
    password: inglife0??
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
  
  sql:
    init:
      mode: never  # 프로덕션에서는 초기 데이터 로드 비활성화
