groups:
  - name: application_alerts
    rules:
      - alert: HighMemoryUsage
        expr: sum(jvm_memory_used_bytes{application="persona-wiki", area="heap"}) / sum(jvm_memory_max_bytes{application="persona-wiki", area="heap"}) > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "JVM 메모리 사용량 높음"
          description: "메모리 사용량이 85%를 초과했습니다: {{ $value | humanizePercentage }}"

      - alert: HighCpuUsage
        expr: process_cpu_usage{application="persona-wiki"} > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "CPU 사용량 높음"
          description: "CPU 사용량이 85%를 초과했습니다: {{ $value | humanizePercentage }}"

      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_seconds_count{application="persona-wiki", status=~"5.."}[1m])) / sum(rate(http_server_requests_seconds_count{application="persona-wiki"}[1m])) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "높은 에러율"
          description: "HTTP 5xx 에러율이 5%를 초과했습니다: {{ $value | humanizePercentage }}"

      - alert: SlowResponses
        expr: http_server_requests_seconds_sum{application="persona-wiki"} / http_server_requests_seconds_count{application="persona-wiki"} > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "느린 응답 시간"
          description: "평균 응답 시간이 500ms를 초과했습니다: {{ $value | humanizeDuration }}"

      - alert: InstanceDown
        expr: up{application="persona-wiki"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "인스턴스 다운"
          description: "인스턴스가 다운되었습니다: {{$labels.instance}}"

  - name: host_alerts
    rules:
      - alert: HighNodeCPU
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "호스트 CPU 사용량 높음"
          description: "서버 CPU 사용량이 80%를 초과했습니다: {{ $value }}%"

      - alert: HighNodeMemory
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "호스트 메모리 사용량 높음"
          description: "서버 메모리 사용량이 85%를 초과했습니다: {{ $value }}%"

      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "디스크 공간 부족"
          description: "디스크 사용량이 85%를 초과했습니다: {{ $value }}%"